version: 2

models:
  - name: cuentas
    columns:
      - name: id
        data_tests:
          - unique
          - not_null

  - name: acreedores
    columns:
      - name: id
        data_tests:
          - unique
          - not_null