
version: 2

models:

  - name: tablas_amortizacion
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: historico_tablas_amortizacion
    columns:
      - name: id
        tests:
          - unique
          - not_null
