version: 2

models:
  - name: domiciliaciones
    columns:
      - name: id
        data_tests:
          - unique
          - not_null

  - name: tablas_amortizacion
    columns:
      - name: id
        data_tests:
          - unique
          - not_null

  - name: historico_tablas_amortizacion
    columns:
      - name: id
        data_tests:
          - unique
          - not_null

  - name: asignacion_acreedores
    columns:
      - name: id
        data_tests:
          - unique
          - not_null