
version: 2

models:
  - name: tablas_amortizacion
    description: "Modelo de transformacion para tablas de amortizacion"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null