version: 2

sources:
  - name: cobranza
    database: creze_dwh
    schema: cobranza
    tables:
      - name: contratos
      - name: tablas_amortizacion
      - name: ban_mcm
      - name: ban_mcd
      - name: cat_tipos_movimiento
      - name: cat_metodos_pago